[custom]

;策略组
custom_proxy_group=🚀 节点选择`select`.*`[]DIRECT
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🤖 AI服务`select`[]🇺🇸 美国节点`[]🚀 节点选择
custom_proxy_group=🏦 金融专线`select`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]DIRECT
custom_proxy_group=📺 YouTube`select`[]🇭🇰 香港节点`[]🚀 节点选择
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🇭🇰 香港节点`[]🚀 节点选择
custom_proxy_group=🛡️ 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT

;节点地区分组
custom_proxy_group=🇺🇸 美国节点`select`(US|美国|USA)
custom_proxy_group=🇭🇰 香港节点`select`(HK|香港)
custom_proxy_group=🇹🇼 台湾节点`select`(TW|台湾)

;规则集
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/InteractiveBrokers/InteractiveBrokers.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/EastWestBank/EastWestBank.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Futu/Futu.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TigerBrokers/TigerBrokers.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/LongBridge/LongBridge.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Snowball/Snowball.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cryptocurrency/Cryptocurrency.list

ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini.list
ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot.list
ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Midjourney/Midjourney.list
ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Poe/Poe.list

ruleset=🇹🇼 台湾节点,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Grok/Grok.list
ruleset=🇹🇼 台湾节点,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Manus/Manus.list
ruleset=🇹🇼 台湾节点,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.list


ruleset=📺 YouTube,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.list
ruleset=📺 YouTube,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.list


ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list


ruleset=🛡️ 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list


ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list

ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,shuziyinpin.vip
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,avid.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,steinberg.net
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,harrisonaudio.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,native-instruments.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,dreamtonics.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,temp-mail.org
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,ilok.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,vsl.co.at
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,mediafire.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,akirabox.to
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,bulianglin.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,inpin.fun
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,bozdigitallabs.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,ddmf.eu
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,kazrog.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,celemony.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,onarworks.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,jackaudio.org
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,izotope.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,uaudio.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,audioease.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,acustica-audio.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,liquidsonics.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,getdante.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,sendowl.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,professionalsupport.dolby.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,fiedler-audio.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,accounts.landr.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,plugin-alliance.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,apulsoft.ch
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,waproduction.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,waves.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,pulsarmodular.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,vertigosound.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,useaudiolabs.de
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,soundtoys.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,orchestraltools.com
ruleset=🎯 全球直现,[]DOMAINS-SUFFIX,synthogy.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,evolutionseries.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,bestservice.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,amplesound.net
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,bigfishaudio.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,kongaudio.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,soundiron.com
ruleset=🎯 全球直连,[]TOONTRACK.COM
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,polyversemusic.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,shop.lovehifi.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,lexiconpro.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,solidstatelogic.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,ams-neve.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,rme-audio.de
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,apiaudio.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,nektartech.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,harmanaudio.in
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,rupertneve.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,0daydown.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,tenlonstudio.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,bianquzy.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,midi123.vip
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,audio-y.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,audioz.download
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,cnblogs.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,midishow.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,midivst.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,vsthouse.ru
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,appstorrent.ru
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,jpsmile.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,filecr.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,shejibaozang.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,macked.app
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,4load.net
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,goaudio.net
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,pluginboutique.com
ruleset=🎯 全球直连,[]DOMAINS-SUFFIX,fuseaudiolabs.de
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,[]GEOIP,CN


ruleset=🐟 漏网之鱼,[]FINAL

enable_rule_generator=true
overwrite_original_rules=true
