[custom]

;策略组
custom_proxy_group=🚀 节点选择`select`.*`[]DIRECT
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🤖 AI服务`select`[]🇺🇸 美国节点`[]🚀 节点选择
custom_proxy_group=🏦 金融专线`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=📺 YouTube`select`[]🇭🇰 香港节点`[]🚀 节点选择
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🇭🇰 香港节点`[]🚀 节点选择
custom_proxy_group=🛡️ 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT


;节点地区分组
custom_proxy_group=🇺🇸 美国节点`select`(US|美国|USA)
custom_proxy_group=🇭🇰 香港节点`select`(HK|香港)
custom_proxy_group=🇹🇼 台湾节点`select`(TW|台湾)


;远程规则集 (Ruleset)

ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/InteractiveBrokers/InteractiveBrokers.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/EastWestBank/EastWestBank.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Futu/Futu.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TigerBrokers/TigerBrokers.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/LongBridge/LongBridge.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Snowball/Snowball.list
ruleset=🏦 金融专线,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cryptocurrency/Cryptocurrency.list

ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini.list
ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot.list
ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Midjourney/Midjourney.list
ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Poe/Poe.list

ruleset=🇹🇼 台湾节点,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Grok/Grok.list
ruleset=🇹🇼 台湾节点,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Manus/Manus.list
ruleset=🇹🇼 台湾节点,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.list

ruleset=📺 YouTube,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.list
ruleset=📺 YouTube,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.list

ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list

ruleset=🛡️ 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list

ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,[]GEOIP,CN

ruleset=🐟 漏网之鱼,[]FINAL



;自定义单条规则 

;金融自定义
custom_rule=DOMAIN-SUFFIX,eastwestbank.com,🏦 金融专线
custom_rule=DOMAIN-SUFFIX,velobank.com,🏦 金融专线
custom_rule=DOMAIN-SUFFIX,longbridge.sh,🏦 金融专线
custom_rule=DOMAIN-SUFFIX,longbridge.hk,🏦 金融专线
custom_rule=DOMAIN-SUFFIX,longbridgeapp.com,🏦 金融专线
custom_rule=DOMAIN-SUFFIX,xueqiu.com,🏦 金融专线

;AI自定义
custom_rule=DOMAIN-SUFFIX,grok.com,🇹🇼 台湾节点
custom_rule=DOMAIN-SUFFIX,manus.im,🇹🇼 台湾节点
custom_rule=DOMAIN-SUFFIX,manus.com,🇹🇼 台湾节点

;音频与工具类直连自定义
custom_rule=DOMAIN-SUFFIX,shuziyinpin.vip,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,avid.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,steinberg.net,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,harrisonaudio.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,native-instruments.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,dreamtonics.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,temp-mail.org,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,ilok.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,vsl.co.at,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,mediafire.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,akirabox.to,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,bulianglin.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,inpin.fun,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,bozdigitallabs.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,ddmf.eu,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,kazrog.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,celemony.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,onarworks.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,jackaudio.org,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,izotope.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,uaudio.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,audioease.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,acustica-audio.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,liquidsonics.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,getdante.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,sendowl.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,professionalsupport.dolby.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,fiedler-audio.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,accounts.landr.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,plugin-alliance.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,apulsoft.ch,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,waproduction.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,waves.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,pulsarmodular.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,vertigosound.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,useaudiolabs.de,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,soundtoys.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,orchestraltools.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,synthogy.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,evolutionseries.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,bestservice.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,amplesound.net,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,bigfishaudio.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,kongaudio.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,soundiron.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,toontrack.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,polyversemusic.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,shop.lovehifi.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,lexiconpro.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,solidstatelogic.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,ams-neve.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,rme-audio.de,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,apiaudio.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,nektartech.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,harmanaudio.in,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,rupertneve.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,0daydown.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,tenlonstudio.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,bianquzy.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,midi123.vip,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,audio-y.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,audioz.download,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,cnblogs.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,midishow.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,midivst.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,vsthouse.ru,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,appstorrent.ru,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,jpsmile.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,filecr.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,shejibaozang.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,macked.app,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,4load.net,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,goaudio.net,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,pluginboutique.com,🎯 全球直连
custom_rule=DOMAIN-SUFFIX,fuseaudiolabs.de,🎯 全球直连

enable_rule_generator=true
overwrite_original_rules=true
